In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [4]:
data = {

"Temperature": ["Hot", "Cold", "Very Hot", "Warm", "Hot", "Warm", "Warm", "Hot", "Hot", "Cold"],

"Color": ["Red", "Yellow", "Blue", "Blue", "Red", "Yellow", "Red", "Yellow", "Yellow", "Yellow"],

"Target": [1, 1, 1, 0, 1, 0, 1, 0, 1, 1]}

df = pd.DataFrame(data, columns = ["Temperature", "Color", "Target"])
df

  Temperature   Color  Target
0         Hot     Red       1
1        Cold  Yellow       1
2    Very Hot    Blue       1
3        Warm    Blue       0
4         Hot     Red       1
5        Warm  Yellow       0
6        Warm     Red       1
7         Hot  Yellow       0
8         Hot  Yellow       1
9        Cold  Yellow       1

In [5]:
print(df['Temperature'].unique())

['Hot' 'Cold' 'Very Hot' 'Warm']

In [6]:
en = LabelEncoder()  # LabelEncoder 클래스를 객체로 생성한 후 encoder의미의 en 참조변수 선언

en.fit(df['Temperature'])  # fit 메소드를 통한 레이블 인코딩

 

df["Temp_Label_Encoder"] = en.transform(df['Temperature']) # transform 메소드를 통한 레이블 인코딩

df

  Temperature   Color  Target  Temp_Label_Encoder
0         Hot     Red       1                   1
1        Cold  Yellow       1                   0
2    Very Hot    Blue       1                   2
3        Warm    Blue       0                   3
4         Hot     Red       1                   1
5        Warm  Yellow       0                   3
6        Warm     Red       1                   3
7         Hot  Yellow       0                   1
8         Hot  Yellow       1                   1
9        Cold  Yellow       1                   0